//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cert2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevelopmentPermit
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string OfficeAddress { get; set; }
        public string ProjectName { get; set; }
        public string ProjectAddress { get; set; }
        public Nullable<bool> Permit { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public string OPNumber { get; set; }
        public string ORNumber { get; set; }
        public Nullable<System.DateTime> ORDate { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserID { get; set; }
    }
}
