//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cert2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP
    {
        public int OpID { get; set; }
        public string Name { get; set; }
        public string OpNumber { get; set; }
        public Nullable<System.DateTime> OpDate { get; set; }
        public string OrNumber { get; set; }
        public Nullable<System.DateTime> OrDate { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string UserID { get; set; }
    }
}
